export const types = {
    // Sync
    FILL_TASKS:  "FILL_TASKS",
    CREATE_TASK: "CREATE_TASK",
    DELETE_TASK: "DELETE_TASK",

    // Async
    FILL_TASKS_ASYNC:  "FILL_TASKS_ASYNC",
    CREATE_TASK_ASYNC: "CREATE_TASK_ASYNC",
    DELETE_TASK_ASYNC: "DELETE_TASK_ASYNC",
};
