export const types = {
    START_FETCHING: "START_FETCHING",
    STOP_FETCHING:  "STOP_FETCHING",

    START_EDITING:          "START_EDITING",
    STOP_EDITING:           "STOP_EDITING",
    UPDATE_EDITING_MESSAGE: "UPDATE_EDITING_MESSAGE",
};
